# fly.toml file generated for redinha-bra on 2022-06-04T15:48:34-04:00

app = "<your-flyio-app-name>"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "41641"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "udp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
